<!doctype html>
<html lang="en">
   <head>
      <meta charset="utf-8">
      <meta name="description" content="">
      <meta name="keywords" content="">
      <meta name="author" content="">
      <meta name="viewport" content="width=device-width, initial-scale=1.0">
      <title>Saas Based B2B B2C Fintech Based Application</title>
       <!--common css-->
       <?php include_once('../common/commoncss.php'); ?>
	   <!--slicl slider css-->
      <link rel="stylesheet" href="../assets/css/slickslider/slick.css" type="text/css"/>
      <link rel="stylesheet" href="../assets/css/slickslider/slick-theme.css" type="text/css"/>
      <link rel="stylesheet" href="../assets/css/slickslider/custom.css" type="text/css"/>
      <!---->
   </head>
   <body>
      <!--header -->
      <?php include_once('../common/topheader.php'); ?>
      <!--slider-->
      <section class="innerBanner">
         <!--navigation-->
         <?php include_once('../common/header.php'); ?>
         <!---->
         <div class="bannerMain">
            <img src="../assets/images/sass-based-b2b-b2c-fintech-based-application-banner.jpg" alt="image"/>
			   <div class="bannerDesc inner">
               <div class="container">
                  <div class="row">
                     <div class="col-sm-12">
                        <h1>SAAS BASED B2B<br> B2C FINTECH<br> APPLICATION</h1>
                       
                     </div>
                  </div>
               </div>
            </div>
         </div>
      </section>
	   <section class="portfolioInner">
	     <div class="container">
		   <div class="row">
				<div class="col-sm-6">
					<div class="portfolioInnerDesc">
					<h2>Saas Based B2B B2C Fintech Based Application</h2>
					<p>The proposed applications' parent company is developing an e-wallet app that enables users to top-up and pay bills with their phones. The proposed application provides aggregation services for information and payment covering mobile recharge, bill payments, government services, insurance, transportation, and many more. The proposed application has approximately 100+ products and is increasing. Unique customer served: 450,000 ++</p>
					<p>The proposed solution provides a solution that enables digital payments to over 100 billers inclusive of mobile top-ups, utility bills, entertainment portals and local councils. A fintech company’s product that provides aggregation services for information and payment covering mobile recharge, bill payments, government services, insurance, transportation, and many more to B2B and B2C market both. </p>
					
					<h3>USP/Features</h3>
					<ul>
						<li>B2B clients can integrate the payment, information, and finance aggregation services on their existing businesses such as e-wallet app, remittance, mobility, e-commerce, accounting, POS machine, app, website etc.</li>
						<li>Payment aggregation- Optimize digital sales by allowing your customers to safely make payments to over 100+ billers.</li>
						<li>Information aggregation- Fetch information straight from government services to automate eKYC process or feed into a credit scoring model.</li>
						<li>Financial aggregation- Get the full picture of customer’s finances – bank accounts, credit cards, loans & many more in one single place.</li>
						<li>Topup and pay bills at a discounted price</li>
						<li>Send money to friends and family</li>
						<li>See your balance and transaction history</li>
						<li>Refer friends and earn commission</li>
					</ul>
					</div>
				</div>
			   <div class="col-sm-6">
					<div class="portfolioInnerImage">
					<!--img src="../assets/images/sass-based-b2b-b2c-fintech-based-application-features-1.jpg" alt="image"-->
					<!-- Image Map Generated by http://www.image-map.net/ -->
						<img src="../assets/images/sass-based-b2b-b2c-fintech-based-application-features-1.jpg" usemap="#image-map">
						
						<map name="image-map">
                            <area target="" alt="JavaScript" title="JavaScript" href="" coords="188,67,190,134,238,134,241,67" shape="poly">
                            <area target="" alt="Moment JS" title="Moment JS" href="" coords="273,71,20" shape="circle">
                            <area target="" alt="React csv" title="React csv" href="" coords="380,96,324,55" shape="rect">
                            <area target="" alt="AWS" title="AWS" href="" coords="128,187,103,203,105,227,164,227,168,213,153,199,140,188,140,187,140,188" shape="poly">
                            <area target="" alt="HTML 5" title="HTML 5" href="" coords="196,168,198,229,217,237,241,228,245,166" shape="poly">
                            <area target="" alt="Redux" title="Redux" href="" coords="286,94,389,105,388,129,271,135,262,106" shape="poly">
                            <area target="" alt="AWS Amplify" title="AWS Amplify" href="" coords="423,83,393,130,455,132" shape="poly">
                            <area target="" alt="Bootstrap" title="Bootstrap" href="" coords="327,229,272,160" shape="rect">
                            <area target="" alt="Material" title="Material" href="" coords="126,245,124,274,167,300,194,285,192,247" shape="poly">
                            <area target="" alt="Sass" title="Sass" href="" coords="219,250,206,278,217,302,276,287,255,251" shape="poly">
                            <area target="" alt="AWS Cognito" title="AWS Cognito" href="" coords="324,236,298,245,294,288,323,301,353,289,352,246" shape="poly">
                            <area target="" alt="React" title="React" href="" coords="361,199,347,225,361,253,397,255,414,227,398,197,385,190,373,194,385,192,385,190" shape="poly">
                            <area target="" alt="npm" title="npm" href="" coords="366,272,444,303" shape="rect">
                            <area target="" alt="jspdf" title="jspdf" href="" coords="249,304,361,337" shape="rect">
                            <area target="" alt="CSS 3" title="CSS 3" href="" coords="137,93,110,114,112,163,139,173,162,168,168,110" shape="poly">
                            <area target="" alt="PHP" title="PHP" href="" coords="353,147,399,136,444,150,433,181,379,184,356,172" shape="poly">
                        </map>
						
						<img src="../assets/images/sass-based-b2b-b2c-fintech-based-application-features-2.jpg" alt="image">
						<img src="../assets/images/sass-based-b2b-b2c-fintech-based-application-technical-3.jpg"  alt="image">
					</div>
				</div>
				
				
			 </div>
		   </div>
	   </section>
	   <section class="portfolioInner portfolioBg">
	     <div class="container">
		   <div class="row">
				<div class="col-sm-6">
					<div class="portfolioInnerImage">
						<img src="../assets/images/sass-based-b2b-b2c-fintech-based-application-technical-2.png" class="mb-5" alt="image">
						<img src="../assets/images/sass-based-b2b-b2c-fintech-based-application-technical-1.png" class="mt-5" alt="image">
					</div>
				</div>
				<div class="col-sm-6">
					<div class="portfolioInnerDesc">
					<h3>TECHNICAL IMPLEMENTATIONS</h3>
					<ul class="mb-0">
						<li>Implemented digital sign on pdf using zoho sign. </li>
						<li>Implemented mini app in react js and integrated with another app. Used iframe and webview for web application and  mobile app respectively.   </li>
						<li>React class components with functional components. For stateful management, replaced with new Hooks like useState, useEffect, useReducer, and useRef. </li>
						<li>Implemented the Drag and Drop functionality using React-Draggable. </li>
						<li>Implemented 2 step authentication for signup with SMS. </li>
						<li>Implemented authentication token to auto-logout after 1 hours of inactive state.</li>
						<li>Developed user interface by using the React JS, Flux for SPA development.</li>
						<li>Worked in using React JS components, Forms, Events, Keys, Router, Animations and Flux concept. </li>
						<li>Worked with backend engineers to optimize existing API calls to create efficiencies by deprecating unneeded API calls. </li>
						<li>Implemented various screens for the front end using React.js and used various predefined components from NPM (Node Package Manager) and redux library. </li>
						<li>Responsible for React UI and architecture. Building components library, including Tree, Slide-View, and Table Grid. </li>
						<li>Implemented React container and presentational components (as Stateless and Functional components when applicable). </li>
						<li>Used Redux-Thunk as middleware to manipulate the data type and handle multiple actions. </li>
						<li>Used lifecycle methods and React Async Await. </li>
						<li>Webpack plugin to perform various tasks that build our application. </li>
						<li>Implemented functionality of social sign-in with google and facebook with aws-amplify </li>
						<li>Implemented Keep me signed in with help of aws-amplify API. </li>
						<li>Used redux-saga as middleware to manipulate the data type and handle multiple actions </li>
						<li>Used Axios to send multiple requests API </li>
						<li>Implemented progress loader when sending multiple requests API with help of axios onUploadProgress function. </li>
						<li>Created a common component for Breadcrumbs, number format. </li>
						<li>Implemented generate pdf using jspdf and jspdf-autotable for grid. </li>
						<li>Created SDK using Swagger Codegen. </li>
						
					</ul>
					</div>
				</div>
			 </div>
		   </div>
	   </section>
	          <section class="commonSlider">
         <div class="container">
            <div class="row">
               <div class="col-sm-12">
                  <div class="commonTitle">
                     <h3>Project Screenshots</h3>
                  </div>
               </div>
               <div class="col-sm-12">
                  <div class="slider center">
                     <div class="slide">
                        <div class="cl">
                           <img src="../assets/images/sass-based-b2b-b2c-fintech-based-application-screenshot-1.jpg" alt="image">
                        </div>
                     </div>
                     <div class="slide">
                        <div class="cl">
                           <img src="../assets/images/sass-based-b2b-b2c-fintech-based-application-screenshot-2.jpg" alt="image">
                        </div>
                     </div>
                     <div class="slide">
                        <div class="cl">
                           <img src="../assets/images/sass-based-b2b-b2c-fintech-based-application-screenshot-3.jpg" alt="image">
                        </div>
                     </div>
                     <div class="slide">
                        <div class="cl">
                           <img src="../assets/images/sass-based-b2b-b2c-fintech-based-application-screenshot-4.jpg" alt="image">
                        </div>
                     </div>
					 <div class="slide">
                        <div class="cl">
                           <img src="../assets/images/sass-based-b2b-b2c-fintech-based-application-screenshot-5.jpg" alt="image">
                        </div>
                     </div>
					 <div class="slide">
                        <div class="cl">
                           <img src="../assets/images/sass-based-b2b-b2c-fintech-based-application-screenshot-6.jpg" alt="image">
                        </div>
                     </div>
					 <div class="slide">
                        <div class="cl">
                           <img src="../assets/images/sass-based-b2b-b2c-fintech-based-application-screenshot-7.jpg" alt="image">
                        </div>
                     </div>
					 <div class="slide">
                        <div class="cl">
                           <img src="../assets/images/sass-based-b2b-b2c-fintech-based-application-screenshot-8.jpg" alt="image">
                        </div>
                     </div>
					 <div class="slide">
                        <div class="cl">
                           <img src="../assets/images/sass-based-b2b-b2c-fintech-based-application-technical-3.jpg"  alt="image">
                        </div>
                     </div>
                  </div>
               </div>
            </div>
         </div>
      </section>
	    <div class="backPortfolio">
	   <a href="/portfolio">Back To Portfolio </a>
	   </div>
      <!--footer-->
      <?php include_once('../common/footer.php'); ?>
      <!--scripts-->
     <?php include_once('../common/commonscripts.php'); ?>
	  <!--slick slider-->
      <!--<script src="assets/js/slickslider/slick.js"></script>-->
      <script src="../assets/js/slickslider/slick1.js"></script>
      <script src="../assets/js/slickslider/custom.js"></script>
	  <!---->
   </body>
</html>